// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// estimate_f_cpp
Rcpp::List estimate_f_cpp(Rcpp::List args);
RcppExport SEXP _mipmapper_estimate_f_cpp(SEXP argsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type args(argsSEXP);
    rcpp_result_gen = Rcpp::wrap(estimate_f_cpp(args));
    return rcpp_result_gen;
END_RCPP
}
// calculate_IBS_cpp
Rcpp::List calculate_IBS_cpp(Rcpp::List args);
RcppExport SEXP _mipmapper_calculate_IBS_cpp(SEXP argsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type args(argsSEXP);
    rcpp_result_gen = Rcpp::wrap(calculate_IBS_cpp(args));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_mipmapper_estimate_f_cpp", (DL_FUNC) &_mipmapper_estimate_f_cpp, 1},
    {"_mipmapper_calculate_IBS_cpp", (DL_FUNC) &_mipmapper_calculate_IBS_cpp, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_mipmapper(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
