# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

estimate_f_cpp <- function(args) {
    .Call(`_mipmapper_estimate_f_cpp`, args)
}

calculate_IBS_cpp <- function(args) {
    .Call(`_mipmapper_calculate_IBS_cpp`, args)
}

